### ISSUE TITLE
could not find the entry

### ISSUE THREAD

**Issue by pony5551** [vovach777/node.pas#7]
Unable to locate program input point http_parser_get_method on dynamic link library D:\svncheck\nodepas\branches\uses_nodepaslib\bin\ ex08_httpserver.exe.

**Comment by vovach777** [comment]
//
// File Checksum Integrity Verifier version 2.05.
//
1793af00c55b273fb03637742ea4c4fe nodepaslib64.dll


Microsoft (R) COFF/PE Dumper Version 10.00.40219.01
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file nodepaslib64.dll

File Type: DLL

  Section contains the following exports for nodepaslib64.dll

    00000000 characteristics
    5C515EE0 time date stamp Wed Jan 30 11:22:56 2019
        0.00 version
           1 ordinal base
        6663 number of functions
        6663 number of names

    ordinal hint RVA      name

       5346 14E1 00006CB0 http_body_is_final
       5347 14E2 000063FE http_errno_description
       5348 14E3 000063B9 http_errno_name
       5349 14E4 00005ECC http_message_needs_eof
       5350 14E5 00005FE4 http_method_str
       5351 14E6 0000193C http_parser_execute
       5352 14E7 00001589 http_parser_get_flags
       5353 14E8 00001559 http_parser_get_http_errno
       5354 14E9 00001571 http_parser_get_http_upgrade
       5355 14EA 0000152F http_parser_get_method
       5356 14EB 00001544 http_parser_get_status_code
       5357 14EC 000062EF http_parser_init
       5358 14ED 00006924 http_parser_parse_url
       5359 14EE 00006C26 http_parser_pause
       5360 14EF 00006CDB http_parser_set_max_header_size
       5361 14F0 00006392 http_parser_settings_init
       5362 14F1 000068FD http_parser_url_init
       5363 14F2 00006CD0 http_parser_version
       5364 14F3 00005F69 http_should_keep_alive
       5365 14F4 00006012 http_status_str

**Comment by vovach777** [comment]
u need compile the nodepasLib in right way.


Target: i686-w64-mingw32 (-mingw64)
Thread model: posix
gcc version 7.4.0 (Rev1, Built by MSYS2 project)


gcc -I. -DHTTP_PARSER_STRICT=0 -fPIC nodepaslib.c http_parser.c -shared -Wl,--whole-archive -luv -lssl -lcrypto -Wl,--no-whole-archive -lpthread -lws2_32 -lpsapi -liphlpapi -lshell32 -lsecur32 -luserenv -luser32 -static
