### ISSUE TITLE
FMX Mobile support?

### ISSUE THREAD

**Issue by windflee** [vovach777/node.pas#8]
Do you have a plan of fmx mobile support? ios and anroid. thank you!

**Comment by windflee** [comment]
Do you have a plan of websocket? thank you!

**Comment by vovach777** [comment]
> Do you have a plan of fmx mobile support? ios and anroid. thank you!

There are no such plans. This is a server framework. In general, I have not tried to build anything for mobile platforms.

> Do you have a plan of websocket? thank you!

Web sockets are in the plans. But I have no feedback on how good the HTTP client model is. On top of it, i can develop  a web socket client. WebSocket Server is in the plans.
